
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ix-exporter
  namespace: "kube-system"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ix-exporter
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes
      - configmaps
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ix-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ix-exporter
subjects:
  - kind: ServiceAccount
    name: ix-exporter
    namespace: "kube-system"

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "ix-exporter"
  namespace: "kube-system"
  labels:
    app.kubernetes.io/name: "ix-exporter"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "ix-exporter"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "ix-exporter"
      name: "ix-exporter"
    spec:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
      nodeSelector:
        ix-exporter: "true"
      priorityClassName: system-node-critical
      serviceAccountName: ix-exporter
      containers:
        - image: "registry.iluvatar.com.cn:10443/k8s/ix-exporter:4.3.0"
          name: "ix-exporter"
          args:
            - --log-level=4
            - --enable-kubernetes=true
            - --ip=0.0.0.0
          securityContext:
            privileged: true
            runAsNonRoot: false
            runAsUser: 0
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: "metrics"
              containerPort: 32021
          volumeMounts:
            - name: pod-resources
              readOnly: true
              mountPath: "/var/lib/kubelet/pod-resources"
            - name: host-proc
              mountPath: /host-proc
              readOnly: true
              mountPropagation: HostToContainer
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
            - name: tmp-dir
              mountPath: "/tmp"
              readOnly: false
      volumes:
        - name: host-proc
          hostPath:
            path: "/proc"
        - name: pod-resources
          hostPath:
            path: "/var/lib/kubelet/pod-resources"
        - name: host-time
          hostPath:
            path: /etc/localtime
        - name: tmp-dir
          hostPath:
            path: "/tmp/iluvatar"
