apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-smartctl-exporter
  namespace: monitoring
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-smartctl-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus-smartctl-exporter
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 20%
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-smartctl-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-smartctl-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9633"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: prometheus-smartctl-exporter
      hostNetwork: false
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
      - name: main
        image: prometheuscommunity/smartctl-exporter:latest
        imagePullPolicy: IfNotPresent
        args:
        - '--smartctl.path=/usr/sbin/smartctl'
        - '--smartctl.interval=60s'
        - '--web.listen-address=0.0.0.0:9633'
        - '--web.telemetry-path=/metrics'
        ports:
        - name: http
          containerPort: 9633
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /hostdev
          name: dev
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-kubelet
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /dev
        name: dev
