apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: npu-exporter
  namespace: monitor
spec:
  selector:
    matchLabels:
      app: npu-exporter
  template:
    metadata:
      labels:
        app: npu-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
        prometheus.io/path: "/metrics"
        prometheus.io/scheme: "http"
    spec:
      nodeSelector:
        accelerator/provider: huawei-npu
      containers:
        - args:
            - umask 027;npu-exporter -port=8082 -ip=0.0.0.0  -updateTime=5 -logFile=/home/hwMindX/npu-exporter.log
              -logLevel=0 -containerMode=docker
          command:
            - /bin/bash
            - -c
            - --
          image: hubimage/npu-exporter:v5.0.RC3
          imagePullPolicy: IfNotPresent
          name: npu-exporter
          ports:
            - containerPort: 8082
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 1000Mi
            requests:
              cpu: "1"
              memory: 1000Mi
          securityContext:
            privileged: true
            runAsGroup: 0
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
            - mountPath: /usr/local/Ascend/driver
              name: ascend-driver
              readOnly: true
            - mountPath: /usr/local/dcmi
              name: ascend-dcmi
              readOnly: true
            - mountPath: /sys
              name: sys
              readOnly: true
            - mountPath: /var/run/dockershim.sock
              name: docker-shim
              readOnly: true
            - mountPath: /var/run/docker
              name: docker
              readOnly: true
            - mountPath: /var/run/cri-dockerd.sock
              name: cri-dockerd
              readOnly: true
            - mountPath: /run/containerd
              name: containerd
              readOnly: true
            - mountPath: /tmp
              name: tmp
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: localtime
        - hostPath:
            path: /usr/local/Ascend/driver
            type: ""
          name: ascend-driver
        - hostPath:
            path: /usr/local/dcmi
            type: ""
          name: ascend-dcmi
        - hostPath:
            path: /sys
            type: ""
          name: sys
        - hostPath:
            path: /var/run/dockershim.sock
            type: ""
          name: docker-shim
        - hostPath:
            path: /var/run/docker
            type: ""
          name: docker
        - hostPath:
            path: /var/run/cri-dockerd.sock
            type: ""
          name: cri-dockerd
        - hostPath:
            path: /run/containerd
            type: ""
          name: containerd
        - hostPath:
            path: /tmp
            type: ""
          name: tmp
