prom/pushgateway: registry.cn-beijing.aliyuncs.com/opshub/prom-pushgateway
grafana/grafana: registry.cn-beijing.aliyuncs.com/opshub/grafana-grafana
ncabatoff/process-exporter: registry.cn-beijing.aliyuncs.com/opshub/ncabatoff-process-exporter
registry.k8s.io/kube-state-metrics/kube-state-metrics: registry.cn-beijing.aliyuncs.com/opshub/registry-k8s-io-kube-state-metrics-kube-state-metrics
# metrics
quay.io/prometheus-operator/prometheus-config-reloader: registry.cn-beijing.aliyuncs.com/opshub/quay-io-prometheus-operator-prometheus-config-reloader
quay.io/prometheus-operator/prometheus-operator: registry.cn-beijing.aliyuncs.com/opshub/quay-io-prometheus-operator-prometheus-operator
registry.k8s.io/metrics-server/metrics-server: registry.cn-beijing.aliyuncs.com/opshub/registry-k8s-io-metrics-server-metrics-server
thanosio/thanos: registry.cn-beijing.aliyuncs.com/opshub/thanosio-thanos
quay.io/prometheus/node-exporter: registry.cn-beijing.aliyuncs.com/opshub/quay-io-prometheus-node-exporter
quay.io/prometheus/alertmanager: registry.cn-beijing.aliyuncs.com/opshub/quay-io-prometheus-alertmanager
quay.io/prometheus/prometheus: registry.cn-beijing.aliyuncs.com/opshub/quay-io-prometheus-prometheus
jimmidyson/configmap-reload: registry.cn-beijing.aliyuncs.com/opshub/jimmidyson-configmap-reload
# nats
nats-streaming: registry.cn-beijing.aliyuncs.com/opshub/nats-streaming
nats: registry.cn-beijing.aliyuncs.com/opshub/nats
natsio/nats-box: registry.cn-beijing.aliyuncs.com/opshub/natsio-nats-box
natsio/prometheus-nats-exporter: registry.cn-beijing.aliyuncs.com/opshub/natsio-prometheus-nats-exporter
natsio/nats-server-config-reloader: registry.cn-beijing.aliyuncs.com/opshub/natsio-nats-server-config-reloader
