apiVersion: apps/v1
kind: Deployment
metadata:
  name: ops-pushgateway
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ops-pushgateway
  template:
    metadata:
      labels:
        app: ops-pushgateway
    spec:
      containers:
      - name: ops-pushgateway
        image: prom/pushgateway:latest
        ports:
        - containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: ops-pushgateway
  namespace: monitoring
spec:
  selector:
    app: ops-pushgateway
  ports:
  - name: metric
    protocol: TCP
    port: 9091
    targetPort: 9091
  type: ClusterIP
