apiVersion: batch/v1
kind: CronJob
metadata:
  name: pushgateway-cleaner
  namespace: monitoring
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            monitoring: "true"
          restartPolicy: OnFailure
          containers:
            - name: cleanup
              image: registry.cn-beijing.aliyuncs.com/opshub/shaowenchen-runtime-ubuntu:18.04
              command:
                - /bin/sh
                - -c
                - |
                  #!/bin/bash
                  PUSHGATEWAY="http://prom-prometheus-pushgateway.kube-system.svc:9091"
                  RETENTION_HOURS=1
                  CURRENT_TS=$(date +%s)

                  echo "Starting cleanup - retention: ${RETENTION_HOURS}h"

                  curl -s "${PUSHGATEWAY}/metrics" | grep "push_time_seconds{" | while read -r line; do
                      JOB=$(echo "$line" | sed 's/.*job="\([^"]*\)".*/\1/')
                      INSTANCE=$(echo "$line" | sed 's/.*instance="\([^"]*\)".*/\1/')
                      PUSH_TIME=$(echo "$line" | awk '{print $2}')
                      
                      AGE_HOURS=$(( (CURRENT_TS - ${PUSH_TIME%.*}) / 3600 ))
                      echo "job=$JOB instance=$INSTANCE age=${AGE_HOURS}h"

                      if [ $AGE_HOURS -gt $RETENTION_HOURS ]; then
                          echo "  Deleting..."
                          if [ "$INSTANCE" = "" ]; then
                              curl -s -X DELETE "${PUSHGATEWAY}/metrics/job/${JOB}"
                          else
                              curl -s -X DELETE "${PUSHGATEWAY}/metrics/job/${JOB}/instance/${INSTANCE}"
                          fi
                      fi
                  done

                  echo "Done"
