apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-query-frontend-cache
  namespace: thanos
data:
  cache-config.yaml: |
    type: IN-MEMORY
    config:
      max_size: 512MB
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query-frontend
  namespace: thanos
  labels:
    app: thanos-query-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-query-frontend
  template:
    metadata:
      labels:
        app: thanos-query-frontend
    spec:
      nodeSelector:
        monitoring: "true"
      containers:
      - name: thanos-query-frontend
        image: registry.cn-beijing.aliyuncs.com/opshub/thanosio-thanos:v0.28.1
        args:
        - query-frontend
        - --log.level=info
        - --query-frontend.downstream-url=http://thanos-query.thanos.svc.cluster.local:10902
        - --http-address=0.0.0.0:9090
        - --query-range.split-interval=24h
        - --query-range.max-retries-per-request=5
        - --query-range.response-cache-config-file=/etc/thanos/cache-config.yaml
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: cache-config
          mountPath: /etc/thanos
          readOnly: true
      volumes:
      - name: cache-config
        configMap:
          name: thanos-query-frontend-cache
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-query-frontend
  namespace: thanos
  labels:
    app: thanos-query-frontend
spec:
  type: NodePort
  selector:
    app: thanos-query-frontend
  ports:
  - name: http
    port: 9090
    targetPort: 9090
    protocol: TCP
