apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: thanos-query
  name: thanos-query
  namespace: thanos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-query
  template:
    metadata:
      labels:
        app: thanos-query
    spec:
      nodeSelector:
        monitoring: "true"
      containers:
      - args:
        - query
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --query.partial-response
        - --query.timeout=2m
        - --query.replica-label=prometheus_replica
        - --query.replica-label=rule_replica
        - --store=dnssrv+thanos-store.monitoring.svc.cluster.local:10901
        - --web.external-prefix=/thanos
        - --web.route-prefix=/thanos
        image: registry.cn-beijing.aliyuncs.com/opshub/thanosio-thanos:v0.28.1
        name: thanos-query
        ports:
        - containerPort: 10902
          name: http
        - containerPort: 10901
          name: grpc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-query
  name: thanos-query
  namespace: thanos
spec:
  type: NodePort
  ports:
  - name: http
    port: 10902
    protocol: TCP
    nodePort: 30902
  - name: grpc
    port: 10901
    protocol: TCP
    nodePort: 30901
  selector:
    app: thanos-query
