apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-stream
  namespace: default
data:
  nginx.conf: |
    server {
      listen 443;
      proxy_connect_timeout 20s;
      proxy_timeout 5m;
      proxy_pass ks3-cn-beijing-internal.ksyuncs.com:443;
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-stream
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-stream
  template:
    metadata:
      labels:
        app: nginx-stream
    spec:
      hostNetwork: true
      nodeSelector:
        nginx-stream: "true"
      containers:
        - name: nginx-stream
          image: registry.cn-beijing.aliyuncs.com/shaowenchen/demo-nginx-stream:latest
          ports:
            - containerPort: 443
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /opt/nginx/stream.conf.d/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-stream
            items:
              - key: nginx.conf
                path: nginx.conf
