apiVersion: v1
kind: Endpoints
metadata:
  name: ops-clickhouse-cluster
  namespace: kube-system
subsets:
  - addresses:
      - ip: 10.10.10.10
    ports:
      - name: metrics
        port: 9363
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ops-clickhouse-cluster
  namespace: kube-system
  labels:
    app: clickhouse
    component: clickhouse
spec:
  ports:
    - name: metrics
      port: 9363
      targetPort: 9363
      protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ops-clickhouse
  namespace: monitoring
  labels:
    ops: "true"
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      component: clickhouse
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scheme: http
