apiVersion: v1
kind: Endpoints
metadata:
  name: ops-ceph-cluster
  namespace: kube-system
subsets:
  - addresses:
      - ip: 10.10.10.10
    ports:
      - name: metrics
        port: 9283
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ops-ceph-cluster
  namespace: kube-system
  labels:
    app: ceph
    component: ceph
spec:
  ports:
    - name: metrics
      port: 9283
      targetPort: 9283
      protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ops-ceph
  namespace: monitoring
  labels:
    ops: "true"
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      component: ceph
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scheme: http
