apiVersion: v1
kind: ServiceAccount
metadata:
  name: hccl-controller
  namespace: mindx-dl
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-hccl-controller-role
rules:
  - apiGroups: ["batch.volcano.sh"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "update","watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","list","watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hccl-controller-rolebinding
subjects:
  - kind: ServiceAccount
    name: hccl-controller
    namespace: mindx-dl
roleRef:
  kind: ClusterRole
  name: pods-hccl-controller-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hccl-controller
  namespace: mindx-dl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hccl-controller
  template:
    metadata:
      labels:
        app: hccl-controller
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      serviceAccountName: hccl-controller
      containers:
      - name: hccl-controller
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        image: registry.cn-beijing.aliyuncs.com/opshub/ascend-hccl-controller:branch_v5.0.0-RC3
        resources:
          requests:
              memory: 300Mi
              cpu: 500m
          limits:
              memory: 300Mi
              cpu: 500m
        imagePullPolicy: IfNotPresent
        command: [ "/bin/bash", "-c", "--"]
        args: ["umask 027;hccl-controller
         -logFile=/home/hwMindX/hccl-controller.log  -logLevel=0   " ]
        volumeMounts:
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
---
