name: ManualCopyTag

on:
  workflow_dispatch:
    inputs:
      src:
        description: ""
        required: true
        default: "quay.io/argoproj/argo-events"
      dest:
        description: ""
        required: true
        default: "registry.cn-beijing.aliyuncs.com/opshub/argoproj-argo-events"
      tag:
        description: ""
        required: true
        default: "v1.8.0"
jobs:
  build:
    name: Image Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: https://registry.cn-beijing.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"
      - name: Working
        run: |
          docker run --rm -v ~/.docker/config.json:/auth.json quay.io/skopeo/stable:v1.13.0 copy docker://${{ inputs.src }}:${{ inputs.tag }} docker://${{ inputs.dest }}:${{ inputs.tag }} --dest-authfile /auth.json --insecure-policy --src-tls-verify=false --dest-tls-verify=false --retry-times 1 --all
